[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "crypto-finetuning"
version = "0.1.0"
description = "密码学领域微调工具 - 使用uv管理"
authors = [
    {name = "Crypto Finetuning Team"}
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "torch>=2.0.0",
    "transformers>=4.36.0",
    "peft>=0.7.0",
    "datasets>=2.14.0",
    "accelerate>=0.24.0",
    "jieba>=0.42.1",
    "opencc-python-reimplemented>=1.1.6",
    "numpy>=1.21.0",
    "tqdm>=4.64.0",
    "scikit-learn>=1.0.0",
    "matplotlib>=3.5.0",
    "seaborn>=0.11.0",
    "pandas>=1.3.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "black>=22.0.0",
    "isort>=5.10.0",
    "flake8>=5.0.0",
]

[project.scripts]
crypto-finetune = "direct_finetuning_with_existing_modules:main"

[tool.uv]
dev-dependencies = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "black>=22.0.0",
    "isort>=5.10.0",
    "flake8>=5.0.0",
]

[tool.black]
line-length = 100
target-version = ['py38']

[tool.isort]
profile = "black"
line_length = 100